<?php
declare(strict_types=1);

/**
 * Envelope encryption over libsodium's secretbox (XSalsa20-Poly1305, AEAD).
 *
 * The master key lives only in APP_KEY, in a file outside the checkout. Losing or
 * rotating it makes every stored credential permanently unreadable — that is the
 * intended failure mode on key loss, but it means the key MUST be pinned in
 * /home/instapod/handoff.env and never regenerated by a deploy.
 */

function master_key(): string {
    $hex = cfg('APP_KEY');
    if ($hex === null) {
        throw new RuntimeException('APP_KEY is not set — refusing to run.');
    }
    $key = @sodium_hex2bin($hex);
    if ($key === false || strlen($key) !== SODIUM_CRYPTO_SECRETBOX_KEYBYTES) {
        throw new RuntimeException('APP_KEY must be 64 hex chars (32 bytes).');
    }
    return $key;
}

/**
 * Returns BASE64 strings, not raw bytes. Raw binary through PDO lands in SQLite as
 * TEXT unless bound as a LOB, and then round-trips only as long as it happens to
 * contain no NUL and no invalid UTF-8 sequence — it will corrupt eventually and
 * silently, and the failure surfaces as an undecryptable customer credential.
 * Base64 removes the whole class of problem for ~33% more bytes.
 *
 * @return array{0:string,1:string} [nonce_b64, ciphertext_b64]
 */
function seal(string $plaintext): array {
    $key   = master_key();
    $nonce = random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
    $ct    = sodium_crypto_secretbox($plaintext, $nonce, $key);
    sodium_memzero($key);
    return [base64_encode($nonce), base64_encode($ct)];
}

function unseal(string $nonceB64, string $ciphertextB64): string {
    $nonce      = base64_decode($nonceB64, true);
    $ciphertext = base64_decode($ciphertextB64, true);
    if ($nonce === false || $ciphertext === false
        || strlen($nonce) !== SODIUM_CRYPTO_SECRETBOX_NONCEBYTES) {
        throw new RuntimeException('Stored record is malformed.');
    }
    $key = master_key();
    $pt  = sodium_crypto_secretbox_open($ciphertext, $nonce, $key);
    sodium_memzero($key);
    if ($pt === false) {
        // Wrong key, or the record was tampered with. Never guess — fail loudly.
        throw new RuntimeException('Decryption failed. APP_KEY may have changed since this was stored.');
    }
    return $pt;
}

/**
 * Same construction as seal()/unseal(), but raw bytes in and out.
 *
 * Share attachments go to a file, not a TEXT column, so the base64 that seal()
 * applies to survive PDO would cost a third of the size for nothing. Layout is
 * nonce || ciphertext, which is why unseal_raw() can split it back apart.
 */
function seal_raw(string $plaintext): string {
    $key   = master_key();
    $nonce = random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);
    $ct    = sodium_crypto_secretbox($plaintext, $nonce, $key);
    sodium_memzero($key);
    return $nonce . $ct;
}

function unseal_raw(string $blob): string {
    $nb = SODIUM_CRYPTO_SECRETBOX_NONCEBYTES;
    if (strlen($blob) <= $nb) {
        throw new RuntimeException('Stored attachment is malformed.');
    }
    $key = master_key();
    $pt  = sodium_crypto_secretbox_open(substr($blob, $nb), substr($blob, 0, $nb), $key);
    sodium_memzero($key);
    if ($pt === false) {
        throw new RuntimeException('Decryption failed. APP_KEY may have changed since this was stored.');
    }
    return $pt;
}

function new_token(): string {
    return bin2hex(random_bytes(24));
}
